src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    #[Assert\NotBlank(
        message: "Le titre ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 200,
        minMessage:"Le titre doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le titre doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $titre = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(
        message: "La marque ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 50,
        minMessage:"La marque doit contenir au minimum {{ limit }} caractères",
        maxMessage:"La marque doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $marque = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(
        message: "Le modele ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 50,
        minMessage:"Le modele doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le modele doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(
        message: "La description ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        minMessage:"La description doit contenir au minimum {{ limit }} caractères",
    )]
    private ?string $description = null;

    #[ORM\Column(length: 200)]
    #[Assert\NotBlank(
        message: "La photo ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 200,
        minMessage:"Le chemin vers la photo doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le chemin vers la photo doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $photo = null;

    #[ORM\Column]
    #[Assert\NotBlank(
        message: "Le prix journalier ne peut pas etre vide",allowNull: false
    )]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'vehicule', targetEntity: Commande::class)]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }
}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('marque')
            ->add('modele')
            ->add('description')
            ->add('photo', FileType::class, [
                'data_class' => null
            ])
            ->add('prix_journalier')
            ->add('submit', SubmitType::class, [
                'label' => $options['labelSubmit'],
                'validate' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
            'labelSubmit' => null
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Vehicule;
use App\Form\FiltreSearchType;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/vehicule')]
class VehiculeController extends EvalAbstractController
{
    #[Route('/admin', name: 'app_vehicule_index', methods: ['GET'])]
    public function index(VehiculeRepository $vehiculeRepository): Response
    {
        if($this->session->has('idVehiculeConnexion')){
            $this->session->remove('idVehiculeConnexion');
        }
        return $this->render('vehicule/index.html.twig', [
            'vehicules' => $vehiculeRepository->findAll(),
        ]);
    }

    #[Route('/admin/new', name: 'app_vehicule_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vehicule = new Vehicule();
        $form = $this->createForm(VehiculeType::class, $vehicule, [
            'labelSubmit' => 'Créer'
        ]);
        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form['photo']->getData() != null){
                $allowedExtensions = ['jpg', 'jpeg', 'png'];
                $file = $form['photo']->getData();
                $originalExtension = $file->getClientOriginalExtension();
                if (!in_array($originalExtension, $allowedExtensions)) {
                    $form->get('photo')->addError(new FormError("L'image doit avoir comme extension jpg, png ou jpeg"));
                }
            }
            if ($form->isValid()) {;
                $fileSystem = new Filesystem();
                $fileName = rand(1, 999999999).'.'.$file->getClientOriginalExtension();
                $fileSystem->copy($file->getPathname(), 'images/' . $fileName);
                $vehicule->setPhoto('images/'.$fileName);
                $vehicule->setDateEnregistrement(new \DateTime('now'));
                $entityManager->persist($vehicule);
                $entityManager->flush();

                return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
            }else{
                $this->showErrorFlash($vehicule);
            }
        }


        return $this->render('vehicule/new.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/admin/{id}/show', name: 'app_vehicule_show', methods: ['GET'])]
    public function show(Vehicule $vehicule): Response
    {
        return $this->render('vehicule/show.html.twig', [
            'vehicule' => $vehicule,
        ]);
    }

    #[Route('/admin/{id}/edit', name: 'app_vehicule_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        $oldFile = $vehicule->getPhoto();
        $form = $this->createForm(VehiculeType::class, $vehicule, [
            'labelSubmit' => 'Modifier'
        ]);
        $form->handleRequest($request);

        if($form->isSubmitted()){
            if($form['photo']->getData() != null) {
                $allowedExtensions = ['jpg', 'jpeg', 'png'];
                $file = $form['photo']->getData();
                $originalExtension = $file->getClientOriginalExtension();
                if (!in_array($originalExtension, $allowedExtensions)) {
                    $form->get('photo')->addError(new FormError("L'image doit avoir comme extension jpg, png ou jpeg"));
                }
            }
            if ($form->isValid()) {
                try {
                    unlink($oldFile);
                } catch (\Exception $e) {
                }
                $fileSystem = new Filesystem();
                $file = $form['photo']->getData();
                $fileName = rand(1, 999999999).'.'.$file->getClientOriginalExtension();
                $fileSystem->copy($file->getPathname(), 'images/' . $fileName);
                $vehicule->setPhoto('images/'.$fileName);
                $entityManager->flush();

                return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
            }else{
                $this->showErrorFlash($vehicule);
            }
        }

        return $this->render('vehicule/edit.html.twig', [
            'vehicule' => $vehicule,
            'form' => $form,
        ]);
    }

    #[Route('/admin/{id}/show', name: 'app_vehicule_delete', methods: ['POST'])]
    public function delete(Request $request, Vehicule $vehicule, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicule->getId(), $request->request->get('_token'))) {
            try {
                unlink($vehicule->getPhoto());
            } catch (\Exception $e) {
            }
            $entityManager->remove($vehicule);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vehicule_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/search', name: 'app_vehicule_search')]
    public function search(Request $request): Response
    {
        $form = $this->createForm(FiltreSearchType::class, null, []);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            if($form->isValid()){
                $data = $form->getData();
                if($form->get('reinitialiser')->isClicked()){
                    foreach ($data as $key => $value){
                        $data[$key] = null;
                    }
                    $form = $this->createForm(FiltreSearchType::class, null, [])->createView();
                }
                $fitreEmpty = true;
                foreach($data as $key => $value){
                    if($value != null){
                        $fitreEmpty = false;
                        break;
                    }
                }
                if($fitreEmpty == false){
                    $vehicule = $this->vehiculeRepository->findVehiculeByDatesAndFiltre($data, $this->session->get('date_deb'), $this->session->get('date_fin'));
                }
            }
        }
        if(!isset($vehicule)){
            $vehicule = $this->vehiculeRepository->findAllVehiculeFree($this->session->get('date_deb'), $this->session->get('date_fin'));
        }
        return $this->render('vehicule/search.html.twig', [
            'form' => $form,
            'vehicules' => $vehicule
        ]);
    }

    #[Route('/{id}/reservation', name: 'app_reservation')]
    public function reservation(Vehicule $vehicule)
    {
        $this->session->set('idVehiculeConnexion', $vehicule->getId());
        return $this->render('reservation/index.html.twig', [
            'vehicules' => $vehicule,
            'dateDeb' => $this->session->has('date_deb') ? $this->session->get('date_deb') : new \DateTime('now'),
            'dateFin' => $this->session->has('date_fin') ? $this->session->get('date_fin') : new \DateTime('now'),
        ]);
    }

    #[Route('/{id}/reservation/create', name: 'app_reservation_create')]
    public function createReservation(Vehicule $vehicule)
    {
        $commande = new Commande();
        $commande->setDateEnregistrement(new \DateTime('now'))
            ->setMembre($this->getUser())
            ->setVehicule($vehicule)
            ->setDateHeurDepart($this->session->get('date_deb'))
            ->setDateHeurFin($this->session->get('date_fin'));
        $this->commandeRepository->add($commande, true);
        return $this->redirectToRoute('homepage');
    }

}

templates/vehicule/_delete_form.html.twig
<form method="post" action="{{ path('app_vehicule_delete', {'id': vehicule.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicule.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/vehicule/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/vehicule/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Modifier Vehicule{% endblock %}

{% block bodyback %}
    <h1>Modifier Vehicule</h1>

    {{ include('vehicule/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_vehicule_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}

templates/vehicule/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Vehicule index{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/scipt.js') }}"></script>
{% endblock %}

{% block bodyback %}
    <h1>Vehicule index</h1>

    <table class="table table-striped" id="myTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Marque</th>
                <th>Modele</th>
                <th>Description</th>
                <th class="imageCollumn">Photo</th>
                <th>Prix_journalier</th>
                <th>Date_enregistrement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for vehicule in vehicules %}
            <tr>
                <td>{{ vehicule.id }}</td>
                <td>{{ vehicule.titre }}</td>
                <td>{{ vehicule.marque }}</td>
                <td>{{ vehicule.modele }}</td>
                <td>{{ vehicule.description }}</td>
                <td><img class="imageIndex" src="{{ asset( vehicule.photo ) }}"></td>
                <td>{{ vehicule.prixJournalier }}</td>
                <td>{{ vehicule.dateEnregistrement ? vehicule.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_vehicule_show', {'id': vehicule.id}) }}" class="btn btn-info">Voire</a>
                    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}" class="btn btn-warning">Modifier</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_new') }}" class="btn btn-success">Créer</a>
{% endblock %}

templates/vehicule/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Vehicule{% endblock %}

{% block bodyback %}
    <h1>Créer Vehicule</h1>

    {{ include('vehicule/_form.html.twig') }}

    <a href="{{ path('app_vehicule_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>
{% endblock %}

templates/vehicule/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vehicule{% endblock %}

{% block body %}
    <p class="d-inline-flex gap-1">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Afficher formulaire pour filtrer
        </button>
    </p>
    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            {{ form(form) }}
        </div>
    </div>
    <h1>Vehicules disponibles</h1>
    {% for vehicule in vehicules %}
        <h2>{{ vehicule.titre }}</h2>
        <img class="imageIndex" src="{{ asset( vehicule.photo ) }}" alt="image voiture">
        <p>{{ vehicule.description }}</p>
        <p>{{ vehicule.prixJournalier }}€ / {{ vehicule.marque }}</p>
        <a href="{{ path('app_reservation', {'id': vehicule.id}) }}" class="btn btn-success">Voire l'offre</a>
        <hr>
    {% endfor %}
    {% if vehicules is empty %}
        <p>Aucun véhicule n'est disponible pour vos date s de réservations</p>
    {% endif %}
{% endblock %}

templates/vehicule/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Vehicule{% endblock %}

{% block bodyback %}
    <h1>Vehicule</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicule.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ vehicule.titre }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ vehicule.marque }}</td>
            </tr>
            <tr>
                <th>Modele</th>
                <td>{{ vehicule.modele }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ vehicule.description }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td><img class="imageIndex" src="{{ asset( vehicule.photo ) }}"></td>
            </tr>
            <tr>
                <th>Prix_journalier</th>
                <td>{{ vehicule.prixJournalier }}€</td>
            </tr>
            <tr>
                <th>Date_enregistrement</th>
                <td>{{ vehicule.dateEnregistrement ? vehicule.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vehicule_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>

    <a href="{{ path('app_vehicule_edit', {'id': vehicule.id}) }}" class="btn btn-warning">Modifier</a>

    {{ include('vehicule/_delete_form.html.twig') }}
{% endblock %}